services:
  grafana:
    image: grafana/grafana:11.3.0
    container_name: shared-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: shared-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:2.9.3
    container_name: shared-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    networks:
      - monitoring-network
    
  alloy:
    image: grafana/alloy:v1.4.0
    container_name: shared-alloy
    command:
      - run
      - /etc/alloy/config.hcl
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./alloy.hcl:/etc/alloy/config.hcl
    depends_on:
      - prometheus
      - loki
    ports:
      - 12345:12345
    networks:
      - monitoring-network

volumes:
  grafana-data:

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
